.TH "src Directory Reference" 3 "Fri Dec 22 2023" "cpp_general_framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBdistance\&.cpp\fP"
.br
.RI "Distance class implementation for abstract distance\&. "
.ti -1c
.RI "file \fBpoint2d\&.cpp\fP"
.br
.RI "Point class developments with 2-dimension\&. "
.in -1c
