.TH "include/geometry/point2d.hpp" 3 "Fri Dec 22 2023" "cpp_general_framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/geometry/point2d.hpp
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBprogrammers::geometry::Point2D\fP"
.br
.RI "\fBPoint2D\fP class with 2-dimensoin\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBprogrammers::geometry\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBPROGRAMMERS_GEOMETRY\fP   _POINT_2D_HPP_"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBAuthor:\fP
.RS 4
Juyeong Jang (jjo4342@gmail.com) 
.RE
.PP
\fBVersion:\fP
.RS 4
1\&.0\&.0 
.RE
.PP
\fBDate:\fP
.RS 4
2023-12-19 
.RE
.PP
\fBCopyright:\fP
.RS 4
Copyright (c) 2023 Juyeong Jang, All Rights Reserved\&. 
.RE
.PP

.PP
Definition in file \fBpoint2d\&.hpp\fP\&.
.SH "Macro Definition Documentation"
.PP 
.SS "#define PROGRAMMERS_GEOMETRY   _POINT_2D_HPP_"

.PP
Definition at line 14 of file point2d\&.hpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for cpp_general_framework from the source code\&.
