.TH "test/unit/point2d.cpp" 3 "Fri Dec 22 2023" "cpp_general_framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
test/unit/point2d.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'geometry/point2d\&.hpp'\fP
.br
\fC#include <cmath>\fP
.br
\fC#include <stdexcept>\fP
.br
\fC#include 'gtest/gtest\&.h'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBprogrammers::geometry\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBprogrammers::geometry::TEST\fP (GeometryPoint2D, Constructor)"
.br
.ti -1c
.RI "\fBprogrammers::geometry::TEST\fP (GeometryPoint2D, AssignmentOperator)"
.br
.ti -1c
.RI "\fBprogrammers::geometry::TEST\fP (GeometryPoint2D, CalculateDistance)"
.br
.ti -1c
.RI "\fBprogrammers::geometry::TEST\fP (GeometryPoint2D, StaticCalculateDistance)"
.br
.ti -1c
.RI "\fBprogrammers::geometry::TEST\fP (GeometryPoint2D, GetX)"
.br
.ti -1c
.RI "\fBprogrammers::geometry::TEST\fP (GeometryPoint2D, GetY)"
.br
.ti -1c
.RI "\fBprogrammers::geometry::TEST\fP (GeometryPoint2D, SetX)"
.br
.ti -1c
.RI "\fBprogrammers::geometry::TEST\fP (GeometryPoint2D, SetY)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for cpp_general_framework from the source code\&.
