.TH "programmers::geometry" 3 "Fri Dec 22 2023" "cpp_general_framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
programmers::geometry
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBPoint2D\fP"
.br
.RI "\fBPoint2D\fP class with 2-dimensoin\&. "
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBTEST\fP (GeometryPoint2D, Constructor)"
.br
.ti -1c
.RI "\fBTEST\fP (GeometryPoint2D, AssignmentOperator)"
.br
.ti -1c
.RI "\fBTEST\fP (GeometryPoint2D, CalculateDistance)"
.br
.ti -1c
.RI "\fBTEST\fP (GeometryPoint2D, StaticCalculateDistance)"
.br
.ti -1c
.RI "\fBTEST\fP (GeometryPoint2D, GetX)"
.br
.ti -1c
.RI "\fBTEST\fP (GeometryPoint2D, GetY)"
.br
.ti -1c
.RI "\fBTEST\fP (GeometryPoint2D, SetX)"
.br
.ti -1c
.RI "\fBTEST\fP (GeometryPoint2D, SetY)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "programmers::geometry::TEST (GeometryPoint2D, Constructor)"

.PP
Definition at line 15 of file point2d\&.cpp\&.
.SS "programmers::geometry::TEST (GeometryPoint2D, AssignmentOperator)"

.PP
Definition at line 22 of file point2d\&.cpp\&.
.SS "programmers::geometry::TEST (GeometryPoint2D, CalculateDistance)"

.PP
Definition at line 28 of file point2d\&.cpp\&.
.SS "programmers::geometry::TEST (GeometryPoint2D, StaticCalculateDistance)"

.PP
Definition at line 44 of file point2d\&.cpp\&.
.SS "programmers::geometry::TEST (GeometryPoint2D, GetX)"

.PP
Definition at line 60 of file point2d\&.cpp\&.
.SS "programmers::geometry::TEST (GeometryPoint2D, GetY)"

.PP
Definition at line 70 of file point2d\&.cpp\&.
.SS "programmers::geometry::TEST (GeometryPoint2D, SetX)"

.PP
Definition at line 81 of file point2d\&.cpp\&.
.SS "programmers::geometry::TEST (GeometryPoint2D, SetY)"

.PP
Definition at line 93 of file point2d\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for cpp_general_framework from the source code\&.
