.TH "thirdparty/install/Debug/GTEST/include/gtest/internal/custom/README.md" 3 "Fri Dec 22 2023" "cpp_general_framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
thirdparty/install/Debug/GTEST/include/gtest/internal/custom/README.md
.SH SYNOPSIS
.br
.PP
.SH "Author"
.PP 
Generated automatically by Doxygen for cpp_general_framework from the source code\&.
